export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';

export const SHOW_LOADER = 'SHOW_LOADER';
export const REDIRECT_TO_HOME = 'REDIRECT_TO_HOME'
export const SET_AUTH_STATUS = 'SET_AUTH_STATUS'
export const SET_ACTIVE_LINK = 'SET_ACTIVE_LINK'
export const DUE_TO_PAY_FETCHED = 'DUE_TO_PAY_FETCHED';